### ISSUE TITLE
Brainstorming Folder Architecture/Packages

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#14]
### Severity level (1-10):

4

### Files/Directories Involved:

\*

### Description:

I don't know if there are any conventions for folder architecture within go projects, but I don't have a clear direction on it as of right now. I'm just naming and grouping things that I think logically belong together. I think it might be beneficial to come up with our own conventions if there are none, or use conventions that already exist. This should probably be addressed before this project gets too large.

**Comment by aaronarduino** [comment]
There aren't really any hard conventions for folder architecture. Most projects kinda comes up with something that works for them. There are lots of big Go projects out there to model after.

Looking around it looks like having all the packages in a `pkg` folder kinda like Grafana would be good: https://github.com/grafana/grafana/tree/master/pkg

**Comment by george-e-shaw-iv** [comment]
So if I renamed the general folder to pkg that would address that. Would I move the public_server and private_server folders into pkg as well? Or keep them out of it?

**Comment by aaronarduino** [comment]
Yeah, that would. Also, the `public_server` and `private_server` folders would need to be moved in there as well.

I can make the necessary changes if you are cool with that folder setup.

**Comment by george-e-shaw-iv** [comment]
I actually just made a lot of changes to follow conventions a lot stricter and I implimented the bare-bones outline for what we just talked about, however I didn't move those folders into there. So I would really appreciate that actually. Let me PR and merge my changes and then you can fetch them and do that. Thank you.

**Comment by george-e-shaw-iv** [comment]
@aaronarduino I'm sure you can pick up on it, but just to make your life easier

private_server -> webhost
public_server -> public

public -> document_roots/public/
private -> document_roots/webhost/

**Comment by aaronarduino** [comment]
That's done with pr #22
