### ISSUE TITLE
Setting up front end development frameworks/package managers/etc

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#20]
### Severity level (1-10):

7

### Files/Directories Involved:

N/A

### Description:

We need to set up NPM (for angular/sass), but we only need it to effect the directory that the private side serves from. We don't need it to effect any other directory other than that.

**Comment by mcrice123** [comment]
Sounds like we just need to add a package.json to _that_ directory and work from there. Question is, what packages should we add to it? I'm looking at the quickstart for Angular for reference. Does anyone else have any suggestions on a good Angular boilerplate?

**Comment by hoangdangninh** [comment]
@humam-nameer-10p
