### ISSUE TITLE
Rolling the ball on client side

### ISSUE THREAD

**Issue by hoangdangninh** [Ennovar/gPanel#25]
### Severity level (1-10):

5

### Files/Directories Involved:

`gPanel/document_roots/webhost`

### Description:

A basic static page on client side which imitates cPanel is needed

### Personal Comments:

HTML, CSS, Bootstrap (as little Javascript as possible)

**Comment by george-e-shaw-iv** [comment]
Just as a side note - we're gonna start with static website development and then once we get a good base translate it into angular code

**Comment by hoangdangninh** [comment]
@byra ;)
