### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#30]
### Severity level (1-10):

3

### Files/Directories Involved:

n/a

### Description:

We need a system of documenting everything that is somewhat important to the project that would not only help contributors but also eventually users. I've been told that using the GitHub wiki might not be the best idea because it adds another layer of abstraction. It was recommended that we should do the documenting within the README.md and we can also link to other markdown documents within it.

So the issue at hand is to decide on a way of documenting, and then get some syntax/conventions started for documenting in general and then more specific syntax/conventions for documenting things like API calls.

**Comment by hoangdangninh** [comment]
英語を話せないよ

**Comment by george-e-shaw-iv** [comment]
I've concluded that README's along with the automatically generated godoc is good enough for right now.
