### ISSUE TITLE
Checking if username already exists in User API Registration

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#35]
### Severity level (1-10):

9

### Files/Directories Involved:

pkg/api/user.go in the UserRegistration func

### Description:

Before inputting the user into the database it needs to check if it already exists, and if it does send back an error and don't process the rest of the request.

### Personal Comments:

I tried already but for some reason couldn't get it to work. Seems like a trivial problem but for some reason I was getting some weird runtime errors. Might give it a shot again later when I have some more time.

**Comment by AustinMCrane** [comment]
depending on the type of database your using (generally with most databases) you can add a unique constraint on a column in a table. then it will throw an sql error you can handle if you wanted to do it that way.

**Comment by george-e-shaw-iv** [comment]
@AustinMCrane For some reason bolt uses the same function (put) as both an updater and an inserter and it doesn't give you any flag or anything to notify you if the key already existed. So I implemented this functionality myself in the database pkg and started to use it in the registration API and it didn't work. Threw some non-fatal runtime errors. I'm gonna give it another go right now and see if I can get it to work. I have a feeling it was a dumb mistake because its a pretty straightforward problem.
