### ISSUE TITLE
BDD testing

### ISSUE THREAD

**Issue by hoangdangninh** [Ennovar/gPanel#37]
### Severity level (1-10):

5

### Files/Directories Involved:

`gPanel/pkg/testing/`

### Description:

Centralize all test cases in 1 places (BDD style) so everyone can contribute in easily

### Personal Comments:

Later on, we can move all of these test cases to CI
PR #36

**Comment by hoangdangninh** [comment]
#5

**Comment by george-e-shaw-iv** [comment]
Someone correct me if I'm wrong but, this isn't the standard way of doing testing in go. Tests should always be written within their relevant package I'm pretty sure.

**Comment by hoangdangninh** [comment]
I think it depends on how deep we want to go with testing. Imagine in an ideal environment where testing and development are 2 sand-boxed environments: testers keep writing tests (all kinds of tests you can think of: smoke test, pen test, stress test, functional test, integration test, system test...), and developers keep developing codes, adhering to an interface...

**Comment by blunket** [comment]
Tests are conventionally written within their relevant package in Go indeed.

**Comment by hoangdangninh** [comment]
yup, trying to follow convention, ran into this https://github.com/Ennovar/gPanel/pull/36#issuecomment-340224884
