### ISSUE TITLE
A list of API calls

### ISSUE THREAD

**Issue by hoangdangninh** [Ennovar/gPanel#39]
### Severity level (1-10):

8

### Files/Directories Involved:

`gPanel/pkg/api`

### Description:

let's brainstorm on a list of API calls

### Personal Comments:

which could serve as an interface for our testers, frontend, and backend developers

**Comment by george-e-shaw-iv** [comment]
@hoangdangninh Good idea, just continue to add to this as more APIs are developed/needed. I kind of set up a little bit of structure within it, hopefully it helps.
