### ISSUE TITLE
Creating secure sessions for users in the backend

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#43]
### Severity level (1-10):

6

### Files/Directories Involved:

N/A

### Description:

I've been toying with it for awhile and I can probably figure it out soon, but I'll just need to practice and really understand how the gorilla/sessions API works before I just start inserting it places. If someone wants to do this before I get around to understanding it then by all means go for it. If you want to set it up in a new package or an existing package, I can use it in the user API to finish that off.

**Comment by hoangdangninh** [comment]
Many people tackle the same issue can be a good thing too as we're able build on the greatness of each other, isn't it the whole point of Git? ;)
