### ISSUE TITLE
Session Store Tests Have No Coverage

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#48]
### Severity level (1-10):

7

### Files/Directories Involved:

pkg/networking/session_store_test.go

### Description:

For some reason when I run this test it says 0.0% statement coverage. I think it has something to do with the fact that I'm running tests on methods that are appended to a struct. I need some insight on this and/or some help.

**Comment by hoangdangninh** [comment]
The single test case looked passing to me. Which command did you use to get that 0.0% coverage?
![image](https://user-images.githubusercontent.com/5388947/32283219-c6f943da-bef1-11e7-820b-2d48a95b8da1.png)

**Comment by george-e-shaw-iv** [comment]
Fixed in some pull request, accidentally didn't reference it.
