### ISSUE TITLE
Tests for Functions

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#5]
### Severity level (1-10):

4

### Files/Directories Involved:

\*

### Description:

Tests need to be written for most, if not all functions in the program.

### Personal Comments:

Tests are written in go, no other language is needed. Check out the [testing](https://golang.org/pkg/testing/) package.

**Comment by hoangdangninh** [comment]
I'm looking into setting up CI to go through all the test cases, has it been done, anyone?

**Comment by hoangdangninh** [comment]
where do we put our test cases currently?

**Comment by george-e-shaw-iv** [comment]
@hoangdangninh Take a look at this https://github.com/ardanlabs/gotraining/tree/master/topics/web/testing for examples. The tests for functions will be under the same packages but in test files using the testing package.
