### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by george-e-shaw-iv** [Ennovar/gPanel#53]
### Severity level (1-10):

1

### Files/Directories Involved:

N/A

### Description:

I think it would be cool to have our own logo, although maybe somewhat unnecessary right now.

**Comment by bvhme** [comment]
I had an idea, what do you think?

![gpanel gopher 0 5x](https://user-images.githubusercontent.com/1917629/39931420-402b5386-5535-11e8-87bf-8295c8d05aca.png)

**Comment by george-e-shaw-iv** [comment]
I love it! I'll implement this into the readme/designs of the project as soon as I can! Do you have a website or anything that you want me to link back to you to give you some credit for the logo? Or just use your GitHub? @bvhme

**Comment by bvhme** [comment]
If you have a list of contributors, feel free to add me, otherwise no credit to me necessary.

**Comment by george-e-shaw-iv** [comment]
I'll work on making a contributor list! Thank you again @bvhme
