### ISSUE TITLE
Work with GOPATH and "go get"

### ISSUE THREAD

**Issue by jcbwlkr** [Ennovar/gPanel#8]
### Severity level (1-10):
8?

### Files/Directories Involved:

All of them

### Description:

Typically for a Go project like this when I run "go get github.com/Ennovar/gPanel" it will clone the project to `$GOPATH/src/github.com/Ennovar/gPanel`. When I try to import packages within the repo it would be like `import "github.com/Ennovar/gPanel/private_server/routing` 

There are a few places where you import like `import "gPanel/private_server/routing"` but that only works if this project is cloned directly to `GOPATH/src/gPanel`.

### Personal Comments:

🍕

**Comment by george-e-shaw-iv** [comment]
So the only thing that would need to be changed is the import paths basically?

**Comment by jcbwlkr** [comment]
yes and anybody who has already cloned the project would need to move their copy to `$GOPATH/src/github.com/Ennovar/gPanel`

**Comment by george-e-shaw-iv** [comment]
As far as deployment works for contributors at that point, would it be something like the following?

```shell
go get github.com/Ennovar/gPanel
cd go/src/github.com/Ennovar
rm -rf gPanel/
git clone https://www.github.com/Username/gPanel.git
cd gPanel
go run main.go
```
Hopefully these aren't dumb assumptions haha. That's where my brain went at least.

**Comment by jcbwlkr** [comment]
It's close. And this is a common question so don't think it's dumb :)

This is a good article about it https://splice.com/blog/contributing-open-source-git-repositories-go/

The summary is contributors would `go get` the project like normal but instead of deleting the folder you can use `git remote add` to add the url to their fork on github. Then when they want to make a contribution they push a change to that fork and open a PR

**Comment by george-e-shaw-iv** [comment]
Oh okay great, didn't realize go get pulled in the .git folder as well. Since we basically just outlined a step-by-step process to do this I'll add the good first contribute tag to this and leave it be for awhile and see if it attracts anyone. If it doesn't attract anyone for an amount of time I'll handle it.
